/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-124278-gcc3ca17127-20260430"
#endif /* AVUTIL_FFVERSION_H */
